#!/bin/bash
# Prompt for required variables for building
read -p "Enter the Firebase project: " FIREBASE_PROJECT
read -p "Enter android package name: " ANDROID_PACKAGE
read -p "Enter ios bundle id: " IOS_BUNDLE

./check_firebase_tools
firebase login

FLUTTER_ROOT_PACKAGE="$(./main_package)"
cd "$FLUTTER_ROOT_PACKAGE" || exit 1

dart pub global activate flutterfire_cli 1.1.0

flutterfire configure --project="${FIREBASE_PROJECT}" \
--token="${FIREBASE_TOKEN}" \
--android-package-name="${ANDROID_PACKAGE}" \
--ios-bundle-id="${IOS_BUNDLE}" \
--platforms=android,ios \
--yes