#!/bin/bash

if [ -z "${FIREBASE_PROJECT}" ]; then
  echo "FIREBASE_PROJECT is not provided. Skipping Firebase initialization."
else
  dart pub global activate flutterfire_cli 1.1.0

  FLUTTER_ROOT_PACKAGE="$(./main_package)"
  cd "$FLUTTER_ROOT_PACKAGE" || exit 1

  flutterfire configure --project="${FIREBASE_PROJECT}" \
    --token="${FIREBASE_TOKEN}" \
    --android-package-name="${ANDROID_PACKAGE}" \
    --platforms=android \
    --yes
fi