#!/bin/bash

if [ -z "${FIREBASE_PROJECT}" ]; then
  echo "FIREBASE_PROJECT is not provided. Skipping Firebase initialization."
else
  dart pub global activate flutterfire_cli 1.1.0

  FLUTTER_ROOT_PACKAGE="$(./main_package)"
  cd "$FLUTTER_ROOT_PACKAGE" || exit 1

  export PATH="$PATH":"$HOME/.pub-cache/bin"

  flutterfire configure --project="${FIREBASE_PROJECT}" \
    --token="${FIREBASE_TOKEN}" \
    --ios-bundle-id="${BUNDLE_ID}" \
    --macos-bundle-id="${BUNDLE_ID}" \
    --platforms=ios \
    --yes
fi