#!/bin/bash

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

./pub_get_packages

FILES=()

# Loop through the results of the find command
while IFS= read -r file; do
  # Use grep to check if the file contains "build_runner"
  if grep -q "build_runner" "$file"; then
    # If the file contains "build_runner", add its path to the FILES array
    FILES+=("$file")
  fi
done < <(find . -name pubspec.yaml -type f)

for file in "${FILES[@]}"; do
  echo "Running build_runner in $file"
  cd "$(dirname "$file")" || exit 1
  dart run build_runner build --delete-conflicting-outputs
  cd "$PROJECT_ROOT" || exit 1
done

while IFS= read -r file; do
  # Use grep to check if the file contains "build_runner"
  if grep -q "intl_utils" "$file"; then
    echo "Running generate intl"
    cd "$(dirname "$file")" || exit 1
    flutter pub global run intl_utils:generate
  fi
done < <(find . -name pubspec.yaml -type f)

echo "Finished running generation packages"
