name: presentation
description: Presentation module
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: ../domain
  localizations:
    path: ../libs/localizations
  utils:
    path: ../libs/utils

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  go_router: ^14.8.1

  flutter_staggered_animations: ^1.1.1

  collection: ^1.19.1

  freezed_annotation: ^2.4.1

  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

