name: domain
description: Domain module
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: ../libs/utils

  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
