name: domain
description: Domain module
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: ../libs/utils

  uuid: ^4.5.1
  collection: ^1.19.1

    # Location services
  geolocator: ^11.0.0
  
  # Overlay window
  flutter_overlay_window: ^0.5.0
  
  # Local notifications
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
